### ISSUE TITLE
Add support for installation of vscode extensions from additional sources

### ISSUE THREAD

**Issue by mristok** [TraGicCode/tragiccode-vscode#30]
Add support for installation of VSCode Extensions from additional sources, such as JFrog Artifactory or from local path. Currently, the assumption is that the node/client running the module is connected to the internet (or via proxy) and can access the Extension Gallery. However, when a system is "air-gapped" this module fails to account for that, and fails due to the validation in vscode_extension type.

**Comment by TraGicCode** [comment]
Hey @mristok ,

Thanks for opening up the issue.  Can you provide me with what you currently do to accomplish installing extensions via a path or jfrog?

Thank you

**Comment by logicminds** [comment]
@mristok yes I would like to know too so I can do the same.

**Comment by TraGicCode** [comment]
Hey @mristok ,

Are you able to provide the details on how you accomplish this currently?

**Comment by TraGicCode** [comment]
@mristok 

Closing this since it's a stale issue.
